name: BBR API Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.16"

      - name: Install dependencies and build project
        run: |
          npm install
          npm run build:esm

      - name: Run tests
        run: |
          cd test
          node index.js